### ISSUE TITLE
Warzone server list

### ISSUE THREAD

**Issue by idan1109** [cetteup/gameserver-lister#2]
Hi, first of all thank you for this beautiful work!! is it possible to retrieve server list for warzone, or for call of duty modern warfare 2019? thank you!

**Comment by cetteup** [comment]
I'll look into it but most newer games make it rather difficult to obtain server lists.

Does the game have custom servers? Or is everything hosted by Activision?

**Comment by idan1109** [comment]
They have 2 datacentres for the profile data then matchmaking servers for searching the matches then an ip is assigned from the matchmaking server when the game starts.. the problem is that everything is in udp I think.. is it a problem?

**Comment by idan1109** [comment]
What I meant is trying to query matchmaking servers… I have really no experience on this kind of stuff so I’m relying on your words!

**Comment by cetteup** [comment]
The key question is: what information are you looking to fetch from the servers?

From my point of view, there's no value in having a list of servers that dynamically changes every few minute as matches start and finish.

With the older/other games, you can query them for their gameplay settings, players on the server or use the details to join the servers directly. None of that is possible with the matchmaking servers.
